apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s-dev/*
      #- ./infra/k8s-cypress/*
build:
  local:
    push: false
  artifacts:
    - image: sadeghsalesi/test-server
      context: server
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: sadeghsalesi/test-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.tsx"
            dest: .
          - src: "**/*.js"
            dest: .
    - image: sadeghsalesi/test-cypress
      context: e2e
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "**/*.js"
            dest: .
